services:
  website:
    image: website
    build: .
    restart: always
    container_name: website
    ports:
      - "4000:80"
    depends_on:
      - db
    volumes:
      - './:/src'
    environment:
      - ASPNETCORE_ENVIRONMENT=Doker
  db:
    image: db
    build: 
      context: .
      dockerfile: db.Dockerfile
    restart: always
    container_name: db
    ports:
      - "8000:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
     - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local